### PR TITLE
Add a tip for those on Mac OSX with homebrew

### PR DESCRIPTION
**Pull request by bdangit**

### CODE REVIEW

**Comment by avsej** [comment]
Hi @bdangit, thank you for contribution, but could you upload it through review system at http://review.couchbase.org?

The guide how to contribute is here: http://developer.couchbase.com/open-source-projects#how-to-contribute-code.

Ask me if you need any further help.

**Comment by bdangit** [comment]
thanks @avsej will do!

**Comment by 7stud** [comment]
The link for installing libcouchbase goes to some irrelevant page.  Here is the link for installing libcouchbase:

https://developer.couchbase.com/server/other-products/release-notes-archives/c-sdk

which on OSX is simply:

    $ brew install libcouchbase

**Comment by avsej** [comment]
@7stud could you publish the patch on http://review.couchbase.org/admin/projects/couchbase-ruby-client?

**Comment by 7stud** [comment]
Also, when I try:

```
require 'couchbase'

conn = Couchbase.connect

```

I get the error:

```
Users/7stud/.rvm/gems/ruby-2.4.0@global/gems/couchbase-1.3.15/lib/couchbase.rb:63:in `initialize':   
bootstrap error, Authentication failed. You may have provided an invalid username/password  
combination 
```

**Comment by avsej** [comment]
server 5 does not allow passwordless buckets anymore. you have to specify credentials

**Comment by 7stud** [comment]
> server 5 does not allow passwordless buckets anymore. you have to specify credentials

Yeah, I got that from the error message.  Could you add the necessary code to _specify credentials_ to the README?

**Comment by 7stud** [comment]
Now I get an error on the `get()`:

```
require 'couchbase' 

client = Couchbase.new( 
    node_list: ['127.0.0.1:8091'],
    bucket: 'beer-sample', 
    username: '7stud', 
    password: 'abc123'
)

val = client.get(
  '21st_amendment_brewery_cafe',
)

p val

--output:--
1.rb:10:in `get': failed to get value, Authentication failed. You may have provided an invalid username/password combination (key="21st_amendment_brewery_cafe", error=0x02) (Couchbase::Error::Auth)
	from 1.rb:10:in `<main>'
```

**Pull request closed without merging**
